# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-DataModel
version:      0.16
version_from: DataModel.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           0
    SQL::Abstract:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
