---
abstract: UML-based Object-Relational Mapping (ORM) framework
author:
  - 'Laurent Dami <laurent.dami AT etat.ge.ch>'
build_requires:
  Task::Weaken: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-DataModel
provides:
  DBIx::DataModel:
    file: lib/DBIx/DataModel.pm
    version: 2.29
  DBIx::DataModel::Compatibility::V0:
    file: lib/DBIx/DataModel/Compatibility/V0.pm
    version: 0
  DBIx::DataModel::Compatibility::V1:
    file: lib/DBIx/DataModel/Compatibility/V1.pm
    version: 0
  DBIx::DataModel::ConnectedSource:
    file: lib/DBIx/DataModel/ConnectedSource.pm
    version: 0
  DBIx::DataModel::Meta:
    file: lib/DBIx/DataModel/Meta.pm
    version: 0
  DBIx::DataModel::Meta::Association:
    file: lib/DBIx/DataModel/Meta/Association.pm
    version: 0
  DBIx::DataModel::Meta::Path:
    file: lib/DBIx/DataModel/Meta/Path.pm
    version: 0
  DBIx::DataModel::Meta::Schema:
    file: lib/DBIx/DataModel/Meta/Schema.pm
    version: 0
  DBIx::DataModel::Meta::Source:
    file: lib/DBIx/DataModel/Meta/Source.pm
    version: 0
  DBIx::DataModel::Meta::Source::Join:
    file: lib/DBIx/DataModel/Meta/Source/Join.pm
    version: 0
  DBIx::DataModel::Meta::Source::Table:
    file: lib/DBIx/DataModel/Meta/Source/Table.pm
    version: 0
  DBIx::DataModel::Meta::Type:
    file: lib/DBIx/DataModel/Meta/Type.pm
    version: 0
  DBIx::DataModel::Meta::Utils:
    file: lib/DBIx/DataModel/Meta/Utils.pm
    version: 0
  DBIx::DataModel::Schema:
    file: lib/DBIx/DataModel/Schema.pm
    version: 0
  DBIx::DataModel::Schema::Generator:
    file: lib/DBIx/DataModel/Schema/Generator.pm
    version: 0
  DBIx::DataModel::Source:
    file: lib/DBIx/DataModel/Source.pm
    version: 0
  DBIx::DataModel::Source::Join:
    file: lib/DBIx/DataModel/Source/Join.pm
    version: 0
  DBIx::DataModel::Source::Table:
    file: lib/DBIx/DataModel/Source/Table.pm
    version: 0
  DBIx::DataModel::Statement:
    file: lib/DBIx/DataModel/Statement.pm
    version: 0
  DBIx::DataModel::Statement::JDBC:
    file: lib/DBIx/DataModel/Statement/JDBC.pm
    version: 0
  DBIx::DataModel::Statement::Oracle:
    file: lib/DBIx/DataModel/Statement/Oracle.pm
    version: 0
  DBIx::DataModel::Table:
    file: lib/DBIx/DataModel/Compatibility/V1.pm
    version: 0
  DBIx::DataModel::View:
    file: lib/DBIx/DataModel/Compatibility/V1.pm
    version: 0
recommends:
  DBD::Mock: 0
  Lingua::EN::Inflect::Number: 0
requires:
  Acme::Damn: 0
  Carp: 0
  DBI: 0
  MRO::Compat: 0
  Module::Build: 0
  Module::Load: 0
  Params::Validate: 0
  SQL::Abstract::More: 1.04
  Scalar::Util: 0
  Storable: 0
  Test::More: 0
  Try::Tiny: 0
  namespace::clean: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 2.29
