---
name: DBIx-DataModel
version: 1.07
author:
  - 'Laurent Dami <laurent.dami AT etat.ge.ch>'
abstract: Classes and UML-style Associations on top of DBI
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  DBI: 0
  Module::Build: 0
  SQL::Abstract: 0
  Test::More: 0
recommends:
  DBD::Mock: 0
  Lingua::EN::Inflect::Number: 0
provides:
  DBIx::DataModel:
    file: lib/DBIx/DataModel.pm
    version: 1.07
  DBIx::DataModel::Base:
    file: lib/DBIx/DataModel/Base.pm
  DBIx::DataModel::Schema:
    file: lib/DBIx/DataModel/Schema.pm
  DBIx::DataModel::Schema::Generator:
    file: lib/DBIx/DataModel/Schema/Generator.pm
  DBIx::DataModel::Source:
    file: lib/DBIx/DataModel/Source.pm
  DBIx::DataModel::Statement:
    file: lib/DBIx/DataModel/Statement.pm
  DBIx::DataModel::Statement::JDBC:
    file: lib/DBIx/DataModel/Statement/JDBC.pm
  DBIx::DataModel::Table:
    file: lib/DBIx/DataModel/Table.pm
  DBIx::DataModel::View:
    file: lib/DBIx/DataModel/View.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
