---
name: DBIx-DataModel
version: 0.31
author:
  - 'Laurent Dami <laurent.dami AT etat.ge.ch>'
abstract: Classes and UML-style Associations on top of DBI
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  DBI: 0
  Module::Build: 0
  SQL::Abstract: 0
  Test::More: 0
recommends:
  DBD::Mock: 0
provides:
  DBIx::DataModel:
    file: lib/DBIx/DataModel.pm
    version: 0.31
  DBIx::DataModel::AbstractTable:
    file: lib/DBIx/DataModel/AbstractTable.pm
  DBIx::DataModel::Base:
    file: lib/DBIx/DataModel/Base.pm
  DBIx::DataModel::Iterator:
    file: lib/DBIx/DataModel/Iterator.pm
  DBIx::DataModel::Schema:
    file: lib/DBIx/DataModel/Schema.pm
  DBIx::DataModel::Table:
    file: lib/DBIx/DataModel/Table.pm
  DBIx::DataModel::View:
    file: lib/DBIx/DataModel/View.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
