---
name: DBIx-DataModel
version: 0.20
author:
  - 'Laurent Dami <laurent.dami AT etat.ge.ch>'
abstract: Classes and UML-style Associations on top of DBI
license: perl
requires:
  Carp: 0
  DBI: 0
  SQL::Abstract: 0
  Test::More: 0
provides:
  DBIx::DataModel:
    file: lib/DBIx/DataModel.pm
    version: 0.20
  DBIx::DataModel::AbstractTable:
    file: lib/DBIx/DataModel/AbstractTable.pm
  DBIx::DataModel::Base:
    file: lib/DBIx/DataModel/Base.pm
  DBIx::DataModel::Iterator:
    file: lib/DBIx/DataModel/Iterator.pm
  DBIx::DataModel::Schema:
    file: lib/DBIx/DataModel/Schema.pm
  DBIx::DataModel::Table:
    file: lib/DBIx/DataModel/Table.pm
  DBIx::DataModel::View:
    file: lib/DBIx/DataModel/View.pm
generated_by: Module::Build version 0.2611
